### ISSUE TITLE
[ Task ] 영상 등록 버튼 기능 구현

### ISSUE THREAD

**Issue by yoonhe** [yoonhe/HomeTrainingManager#12]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail: 영상 등록 버튼 클릭시 선택된 운동 영상이 오늘의 운동 리스트에 등록되어야 합니다

## TODO
1. [ ] 영상 등록 버튼 기능 클릭시 선택된 영상이 로컬스토리지의 `todayVideos` key의 value로 저장된다
2. [ ] 영상 등록 버튼 기능 클릭시 모달이 닫긴다
3. [ ] 변경된 `todayVideos`를 기준으로 비디오 컴포넌트가 리렌더링 된다

## Labels
- Estimated time: `E: 1h`
- Group: `client`
- Sprint : `Sprint3`
- Urgency: `Middle`
