### ISSUE TITLE
[ Task ] 기술 스택 선택

### ISSUE THREAD

**Issue by yoonhe** [yoonhe/HomeTrainingManager#3]
## ISSUE
- Group: `sr`
- Detail: 프로젝트 진행에 사용할 기술 스택 선택

## TODO
1. [x] 기술 스택 조사
2. [x] 클라이언트 기술 스택 선택 - React
3. [x] 서버 기술 스택 선택 - 파이어 베이스 사용 

## Labels
- Estimated time: `E: 2h`
- Group: `sr`
- Sprint : `Sprint1`
- Urgency: `상`

**Comment by yoonhe** [comment]
- Javscript, React
- jest, testing library
