### ISSUE TITLE
[ Task ] 프로젝트 개발 환경 구축

### ISSUE THREAD

**Issue by yoonhe** [yoonhe/HomeTrainingManager#4]
## ISSUE
- Group: `client`
- Type: `setting`
- Detail: initial setting

## TODO
1. [x] 초기 개발 환경 구축
1. [x] 코드 컨벤션 통일 - ESlint, Prettier
2. [x] 커밋 메시지 규칙  - https://github.com/yoonhe/HomeTrainingManager/issues/4#issuecomment-962387341
4. [x] 브랜치 생성 규칙 - https://github.com/yoonhe/HomeTrainingManager/issues/4#issuecomment-975118066

## Labels
- Estimated time: `E: 1h`
- Group: `client`
- Sprint : `Sprint2`
- Urgency: `Middle`

**Comment by yoonhe** [comment]
| **Usage**  | **Commit Type** |
|:---------------:|:---------:|
|이니셜 커밋|init:|
|새로운 기능 구현|feat:|
|버그 해결, 잘못된 코드 변경|fix:|
|코드 리팩토링|refactor:|
|문서작업(README)|docs:|
|UI 스타일링|style:|

**Comment by yoonhe** [comment]
### 브랜치 생성 규칙

기능단위로 브랜치를 생성한다. <br>
브랜치명은 아래와 같은 규칙을 따른다.<br>
`커밋타입 / 기능 / 이슈번호` <br>
ex.
```
feature/product_page/3

refactor/filter/6
```
